### Import Necessary Libraries

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Loading the Dataset

In [8]:
pd.set_option('display.max_columns', None)
df = pd.read_csv('NYC.csv', encoding='latin-1')
df.head()

,id,vendor_id,pickup_datetime,dropoff_datetime,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration
0,id2875421,2,2016-03-14 17:24:55,2016-03-14 17:32:30,1,-73.982155,40.767937,-73.964630,40.765602,N,455
1,id2377394,1,2016-06-12 00:43:35,2016-06-12 00:54:38,1,-73.980415,40.738564,-73.999481,40.731152,N,663
2,id3858529,2,2016-01-19 11:35:24,2016-01-19 12:10:48,1,-73.979027,40.763939,-74.005333,40.710087,N,2124
3,id3504673,2,2016-04-06 19:32:31,2016-04-06 19:39:40,1,-74.010040,40.719971,-74.012268,40.706718,N,429
4,id2181028,2,2016-03-26 13:30:55,2016-03-26 13:38:10,1,-73.973053,40.793209,-73.972923,40.782520,N,435

### Data Understanding

In [13]:
df.describe()

,vendor_id,pickup_datetime,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,trip_duration,trip_duration_in_minutes
count,1.458644e+06,1458644,1.458644e+06,1.458644e+06,1.458644e+06,1.458644e+06,1.458644e+06,1.458644e+06,1.458644e+06
mean,1.534950e+00,2016-04-01 10:10:24.940037120,1.664530e+00,-7.397349e+01,4.075092e+01,-7.397342e+01,4.075180e+01,9.594923e+02,1.599154e+01
min,1.000000e+00,2016-01-01 00:00:17,0.000000e+00,-1.219333e+02,3.435970e+01,-1.219333e+02,3.218114e+01,1.000000e+00,1.666667e-02
25%,1.000000e+00,2016-02-17 16:46:04.249999872,1.000000e+00,-7.399187e+01,4.073735e+01,-7.399133e+01,4.073588e+01,3.970000e+02,6.616667e+00
50%,2.000000e+00,2016-04-01 17:19:40,1.000000e+00,-7.398174e+01,4.075410e+01,-7.397975e+01,4.075452e+01,6.620000e+02,1.103333e+01
75%,2.000000e+00,2016-05-15 03:56:08.750000128,2.000000e+00,-7.396733e+01,4.076836e+01,-7.396301e+01,4.076981e+01,1.075000e+03,1.791667e+01
max,2.000000e+00,2016-06-30 23:59:39,9.000000e+00,-6.133553e+01,5.188108e+01,-6.133553e+01,4.392103e+01,3.526282e+06,5.877137e+04
std,4.987772e-01,NaN,1.314242e+00,7.090186e-02,3.288119e-02,7.064327e-02,3.589056e-02,5.237432e+03,8.729053e+01

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1458644 entries, 0 to 1458643
Data columns (total 12 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   id                        1458644 non-null  object
 1   vendor_id                 1458644 non-null  int64
 2   pickup_datetime           1458644 non-null  datetime64[ns]
 3   dropoff_datetime          1458644 non-null  object
 4   passenger_count           1458644 non-null  int64
 5   pickup_longitude          1458644 non-null  float64
 6   pickup_latitude           1458644 non-null  float64
 7   dropoff_longitude         1458644 non-null  float64
 8   dropoff_latitude          1458644 non-null  float64
 9   store_and_fwd_flag        1458644 non-null  object
 10  trip_duration             1458644 non-null  int64
 11  trip_duration_in_minutes  1458644 non-null  float64
dtypes: datetime64[ns](1), float64(5), int64(3), object(3)
memory usage: 133.5+ MB

In [15]:
df.isnull().sum()

id                          0
vendor_id                   0
pickup_datetime             0
dropoff_datetime            0
passenger_count             0
pickup_longitude            0
pickup_latitude             0
dropoff_longitude           0
dropoff_latitude            0
store_and_fwd_flag          0
trip_duration               0
trip_duration_in_minutes    0
dtype: int64

In [16]:
df.duplicated().sum()

0

In [21]:
df.shape

(1458644, 7)

In [22]:
df.size

10210508

In [3]:
df['store_and_fwd_flag'].value_counts()

store_and_fwd_flag
N    1450599
Y       8045
Name: count, dtype: int64

### Data Structuring

In [11]:
df['pickup_datetime'] = pd.to_datetime(df['pickup_datetime'])
df.dtypes

id                            object
vendor_id                      int64
pickup_datetime       datetime64[ns]
dropoff_datetime              object
passenger_count                int64
pickup_longitude             float64
pickup_latitude              float64
dropoff_longitude            float64
dropoff_latitude             float64
store_and_fwd_flag            object
trip_duration                  int64
dtype: object

In [12]:
df['trip_duration_in_minutes'] = df['trip_duration'] / 60

In [17]:
df.drop(columns=['id','pickup_longitude','pickup_latitude','dropoff_longitude','dropoff_latitude'], inplace=True)

In [18]:
df.head()

,vendor_id,pickup_datetime,dropoff_datetime,passenger_count,store_and_fwd_flag,trip_duration,trip_duration_in_minutes
0,2,2016-03-14 17:24:55,2016-03-14 17:32:30,1,N,455,7.583333
1,1,2016-06-12 00:43:35,2016-06-12 00:54:38,1,N,663,11.050000
2,2,2016-01-19 11:35:24,2016-01-19 12:10:48,1,N,2124,35.400000
3,2,2016-04-06 19:32:31,2016-04-06 19:39:40,1,N,429,7.150000
4,2,2016-03-26 13:30:55,2016-03-26 13:38:10,1,N,435,7.250000

#### Outliers Filtering

In [19]:
outliers = df[(df['trip_duration_in_minutes'] < 1) | (df['trip_duration_in_minutes'] > 120)]
outliers.head()

,vendor_id,pickup_datetime,dropoff_datetime,passenger_count,store_and_fwd_flag,trip_duration,trip_duration_in_minutes
72,2,2016-02-20 21:58:13,2016-02-20 21:59:10,1,N,57,0.950000
323,1,2016-06-27 11:22:37,2016-06-27 11:23:17,1,N,40,0.666667
531,2,2016-02-20 04:03:06,2016-02-21 03:33:00,3,N,84594,1409.900000
842,2,2016-05-21 12:46:46,2016-05-21 12:46:49,2,N,3,0.050000
853,2,2016-03-29 22:39:46,2016-03-29 22:40:44,5,N,58,0.966667

In [20]:
outliers.shape

(10848, 7)

In [23]:
df = df[~df.index.isin(outliers.index)] # Remove outliers from the original DataFrame
df.shape # Check the shape of the DataFrame after removing outliers

(1447796, 7)

In [24]:
new_df = df.copy()
new_df.drop(columns=['trip_duration','store_and_fwd_flag'], inplace=True)

In [41]:
new_df['hour_of_day'] = new_df['pickup_datetime'].dt.hour
new_df['day_of_week'] = new_df['pickup_datetime'].apply(lambda x: x.isoweekday())
new_df['month_of_year'] = new_df['pickup_datetime'].dt.month
new_df.head()

,vendor_id,pickup_datetime,dropoff_datetime,passenger_count,trip_duration_in_minutes,hour_of_day,day_of_week,month_of_year
0,2,2016-03-14 17:24:55,2016-03-14 17:32:30,1,7.583333,17,1,3
1,1,2016-06-12 00:43:35,2016-06-12 00:54:38,1,11.050000,0,7,6
2,2,2016-01-19 11:35:24,2016-01-19 12:10:48,1,35.400000,11,2,1
3,2,2016-04-06 19:32:31,2016-04-06 19:39:40,1,7.150000,19,3,4
4,2,2016-03-26 13:30:55,2016-03-26 13:38:10,1,7.250000,13,6,3

In [42]:
peek_offpeek_hours= new_df.groupby('hour_of_day')['trip_duration_in_minutes'].count().reset_index( name='trip_count').set_index('hour_of_day')
peek_offpeek_hours= peek_offpeek_hours.sort_values(by='trip_count', ascending=False)
peek_offpeek_hours

             trip_count
hour_of_day
18                90022
19                89753
21                83607
20                83536
22                79936
17                75910
14                73697
12                71370
15                71223
13                70976
23                69306
11                68024
9                 67253
8                 66662
10                65032
16                63758
7                 55213
0                 52775
1                 38221
6                 32933
2                 27661
3                 20637
4                 15524
5                 14767

In [43]:
weekday_trips= new_df.groupby('day_of_week')['trip_duration_in_minutes'].count().reset_index(name='trip_count').set_index('day_of_week').sort_values(by='trip_count', ascending=False)
weekday_trips = weekday_trips.sort_values(by='trip_count', ascending=False)
weekday_trips

             trip_count
day_of_week
5                221870
6                219190
4                216947
3                208751
2                201318
7                193669
1                186051

In [44]:
average_trip_duration_by_hour = new_df.groupby('hour_of_day')['trip_duration_in_minutes'].mean().reset_index(name='average_trip_duration').set_index('hour_of_day').sort_values(by='average_trip_duration', ascending=False)
average_trip_duration_by_hour

             average_trip_duration
hour_of_day
15                       16.164062
16                       16.158841
14                       15.856380
17                       15.595790
13                       15.010536
12                       14.696227
11                       14.659226
18                       14.398233
10                       14.189638
9                        14.120025
8                        13.963393
23                       13.607323
22                       13.472555
19                       13.222705
0                        13.099148
21                       12.999611
20                       12.864063
7                        12.703321
1                        12.406891
4                        12.380970
5                        12.006863
3                        11.809817
2                        11.788360
6                        11.266490

In [46]:
new_df.groupby('vendor_id').agg({'trip_duration_in_minutes': 'mean'}).reset_index().sort_values(by='trip_duration_in_minutes', ascending=False)

   vendor_id  trip_duration_in_minutes
1          2                 14.084657
0          1                 13.933970